name: "✨ Feature"
description: "새로운 기능 추가"
labels: ["feature"]
body:
  - type: textarea
    attributes:
      label: 📄 기능 설명
      description: 어떤 기능인가요?
      placeholder: 자세히 적을수록 코드 리뷰할 때 편해요!
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✅ 작업 상세 내용
      description: 할 일을 체크박스 형태로 작성해주세요.
      placeholder: 최대한 세분화해서 적어주세요!
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🙋🏻 참고할만한 자료(선택)
      description: 참고 자료가 있다면 작성해 주세요.
